[server]
data-path = "Data/raft-kvs"
log-path = "Logs/raft-kvs"
log-level = "info"

[cluster]
[[cluster.nodes]]
node-id=1
host="localhost"
http-port=9001
heartbeat-port=9101
replicate-port=9201

[[cluster.nodes]]
node-id=2
host="localhost"
http-port=9002
heartbeat-port=9102
replicate-port=9302

[[cluster.nodes]]
node-id=3
host="localhost"
http-port=9003
heartbeat-port=9103
replicate-port=9203

# [[cluster.nodes]]
# node-id=4
# host="n4"
# http-port=9991
# heartbeat-port=9992
# replicate-port=9993

# [[cluster.nodes]]
# node-id=5
# host="n5"
# http-port=9991
# heartbeat-port=9992
# replicate-port=9993
